# fix "Unsupported Ruby version 2.1" raised by rainbow-3.0.0 on travis-ci
# see: https://github.com/rubocop-hq/rubocop/issues/6398
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - test/dummy/bin/*
    - db/schema.rb
    - test/dummy/db/schema.rb
    - db/migrate/*
    - test/dummy/db/migrate/*
    - test/fixtures/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
